language: node_js

node_js:
  - 'lts/*'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install: yarn install

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn run test
